### ISSUE TITLE
New enemy evolutions

### ISSUE THREAD

**Issue by RichardChase** [pabloleban/idle-slayer-site#25]
Updated enemy evolutions. Let me know if i did this right.
[enemies.js.txt](https://github.com/pabloleban/idle-slayer-site/files/9543114/enemies.js.txt)

Wasnt sure if I could do giants as I wasnt sure if that file supported "evolutions" and "base" for the jade hills giant

**Comment by pabloleban** [comment]
Thanks!
Giants evolution is not yet supported unfortunatelly.
